version: '3'

services:
  scrapy_service:
    build:
      context: .
      target: dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: devdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      TZ: America/Sao_Paulo
    command: sh -c "playwright install --with-deps chromium && python run_spider.py"

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  dev-db-data:
